basePath: /api/v1
definitions:
  http.CreateCurrencyReq:
    properties:
      symbol:
        type: string
    required:
    - symbol
    type: object
  http.ErrMsg:
    properties:
      error:
        type: string
    type: object
  model.Currency:
    properties:
      id:
        type: integer
      symbol:
        type: string
    type: object
  model.CurrencyPrice:
    properties:
      currencyID:
        type: integer
      id:
        type: integer
      price:
        type: number
      time:
        type: integer
    type: object
  model.CurrencyPriceInterval:
    properties:
      close_price:
        type: number
      close_time:
        type: integer
      high_price:
        type: number
      low_price:
        type: number
      open_price:
        type: number
      open_time:
        type: integer
    type: object
  model.GetCurrencyPriceHistoricalDTORes:
    properties:
      max_page:
        type: integer
      page:
        type: integer
      prices:
        items:
          $ref: '#/definitions/model.CurrencyPriceInterval'
        type: array
    type: object
  model.GetCurrencyStat24HDTO:
    properties:
      close_time:
        type: integer
      high_price:
        type: number
      last_price:
        type: number
      low_price:
        type: number
      open_price:
        type: number
      open_time:
        description: |-
          Volume      float64 `json:"volume,string"`
          QuoteVolume float64 `json:"quoteVolume,string"`
        type: integer
      symbol:
        type: string
    type: object
info:
  contact: {}
  description: Gexabyte test assignment
  title: Gexabyte
  version: "1.0"
paths:
  /currencies:
    get:
      description: Retrieves a list of tracked currencies.
      produces:
      - application/json
      responses:
        "200":
          description: Retrieves a list of tracked currencies
          schema:
            items:
              items:
                $ref: '#/definitions/model.Currency'
              type: array
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/http.ErrMsg'
      summary: List currencies
      tags:
      - currency
  /currency:
    post:
      consumes:
      - application/json
      description: Creates a new tracked pair.
      parameters:
      - description: Currency to create
        in: body
        name: currency
        required: true
        schema:
          $ref: '#/definitions/http.CreateCurrencyReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/http.ErrMsg'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/http.ErrMsg'
      summary: Create
      tags:
      - currency
  /ping:
    get:
      description: Returns a 200 OK status to indicate the service is up and running
      responses:
        "200":
          description: OK
      summary: Ping endpoint
      tags:
      - ping
  /prices:
    get:
      description: Retrieves a list of current currency prices.
      produces:
      - application/json
      responses:
        "200":
          description: A list of current currency prices
          schema:
            items:
              items:
                $ref: '#/definitions/model.CurrencyPrice'
              type: array
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/http.ErrMsg'
      summary: List currency prices
      tags:
      - prices
  /prices/current:
    get:
      description: Retrieves current prices fof symbols and save it in db.
      parameters:
      - description: symbols
        example: '["BTCUSDT", "ETHUSDT"]'
        in: query
        name: symbols
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.CurrencyPrice'
            type: array
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/http.ErrMsg'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/http.ErrMsg'
      summary: Get purrent prices of symbols
      tags:
      - prices
  /prices/historical:
    get:
      description: Retrieves historical prices for a currency based on the specified
        parameters. Requires `symbol`, `interval`, `startTime`, `endTime`, `page`,
        and `limit` query parameters.
      parameters:
      - description: Currency symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: Interval
        enum:
        - 1s
        - 1m
        - 3m
        - 5m
        - 15m
        - 30m
        - 1h
        - 2h
        - 4h
        - 6h
        - 8h
        - 12h
        - 1d
        - 3d
        - 1w
        - 1M
        in: query
        name: interval
        required: true
        type: string
      - description: Start time in Unix timestamp milliseconds
        in: query
        name: startTime
        required: true
        type: integer
      - description: End time in Unix timestamp milliseconds
        in: query
        name: endTime
        required: true
        type: integer
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      - description: Max limit is 1000
        in: query
        maximum: 1000
        minimum: 1
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successful response with historical price data
          schema:
            items:
              $ref: '#/definitions/model.GetCurrencyPriceHistoricalDTORes'
            type: array
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/http.ErrMsg'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/http.ErrMsg'
      summary: List historical currency prices
      tags:
      - prices
  /stat/24h:
    get:
      description: Retrieves 24-hour statistics for the specified symbols.
      parameters:
      - description: symbols
        example: '["BTCUSDT", "ETHUSDT"]'
        in: query
        name: symbols
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.GetCurrencyStat24HDTO'
            type: array
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/http.ErrMsg'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/http.ErrMsg'
      summary: Get 24h statistics
      tags:
      - stat
swagger: "2.0"
